# Generated by Django 4.1.3 on 2022-11-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('song', models.FileField(upload_to='songs')),
                ('thumbnail', models.FileField(upload_to='thumbnail')),
            ],
        ),
    ]
